# 사용할 베이스 이미지 설정 (alpine - 경량화)
FROM redis:7.2.4-alpine

# 컨테이너에 필요한 파일 복사
COPY dockerfile/redis/redis.conf /usr/local/etc/redis/redis.conf

# 컨테이너 내에서 사용할 포트 설정
EXPOSE 6379

# 컨테이너 시작 시 실행할 명령 설정
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]