version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT:6379
    restart: always
    volumes:
      - ../redis-data:/data
    networks:
      - msa-api-network

  api:
    image: redis-api:latest
    container_name: redis-api
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile-local
    ports:
      - "9001:9001"
    environment:
      - PORT=9001
      - NODE_ENV=local
      - REDIS_HOST_ENV=redis
    restart: always
    depends_on:
      - redis
    networks:
      - msa-api-network

networks:
  msa-api-network: