# 기본 이미지 설정
FROM node:18

# install npm (전역에 v.10.2.3으로)
RUN npm install -g npm@10.2.3

# update apt-get
RUN apt-get update

# clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 생성
WORKDIR /app/redis-api

# 소스 코드 복사
COPY . .

# 앱을 실행할 사용자 생성
RUN chown -R node:node .

# 실행하는 프로세스의 사용자를 생성한 사용자로 변경
USER node

# npm cache
RUN npm ci && npm cache clean --force

# 앱 빌드
RUN npm run build

# 컨테이너 실행 시 실행될 명령어 설정
CMD ["npm", "run", "start:dev"]